# Generated by Django 3.1.1 on 2020-09-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200905_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
