# Generated by Django 3.1.1 on 2020-09-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200905_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machinery',
            new_name='Machinerie',
        ),
    ]
